In [1]:
A = [1 2; 3 4; 5 6]

A =

   1   2
   3   4
   5   6



In [2]:
B = [11 12; 13 14; 15 16]

B =

   11   12
   13   14
   15   16



In [3]:
C = [1 1; 2 2]

C =

   1   1
   2   2



In [4]:
A*C

ans =

    5    5
   11   11
   17   17



In [5]:
A .* B

ans =

   11   24
   39   56
   75   96



In [6]:
A .^ 2

ans =

    1    4
    9   16
   25   36



In [7]:
v = [1; 2; 3]

v =

   1
   2
   3



In [8]:
1 ./ v

ans =

   1.00000
   0.50000
   0.33333



In [9]:
1 ./ A

ans =

   1.00000   0.50000
   0.33333   0.25000
   0.20000   0.16667



In [10]:
log(v)

ans =

   0.00000
   0.69315
   1.09861



In [11]:
exp(v)

ans =

    2.7183
    7.3891
   20.0855



In [13]:
abs([-1;2;-3])

ans =

   1
   2
   3



In [14]:
-v

ans =

  -1
  -2
  -3



In [15]:
v + ones(length(v), 1)

ans =

   2
   3
   4



In [16]:
v + 1

ans =

   2
   3
   4



In [17]:
A

A =

   1   2
   3   4
   5   6



In [18]:
A'

ans =

   1   3   5
   2   4   6



In [20]:
(A')'

ans =

   1   2
   3   4
   5   6



In [21]:
a = [1 15 2 0.5]

a =

    1.00000   15.00000    2.00000    0.50000



In [22]:
max(a)

ans =  15


In [23]:
min(a)

ans =  0.50000


In [24]:
[val, ind] = max(a)

val =  15
ind =  2


In [25]:
max(A)

ans =

   5   6



In [27]:
disp(a)
a < 3

    1.00000   15.00000    2.00000    0.50000
ans =

  1  0  1  1



In [28]:
find(a < 3)

ans =

   1   3   4



In [29]:
A = magic(3)

A =

   8   1   6
   3   5   7
   4   9   2



In [30]:
help magic

'magic' is a function from the file /usr/share/octave/4.2.2/m/special-matrix/magic.m

 -- magic (N)

     Create an N-by-N magic square.

     A magic square is an arrangement of the integers '1:n^2' such that
     the row sums, column sums, and diagonal sums are all equal to the
     same value.

     Note: N must be a scalar greater than or equal to 3.  If you supply
     N less than 3, magic returns either a nonmagic square, or else the
     degenerate magic squares 1 and [].

Additional help for built-in functions and operators is
available in the online version of the manual.  Use the command
'doc <topic>' to search the manual index.

Help and information about Octave is also available on the WWW
at http://www.octave.org and via the help@octave.org
mailing list.


In [31]:
[r, c] = find(A >= 7)

r =

   1
   3
   2

c =

   1
   2
   3



In [33]:
a

a =

    1.00000   15.00000    2.00000    0.50000



In [34]:
sum(a)

ans =  18.500


In [35]:
prod(a)

ans =  15


In [36]:
floor(a)

ans =

    1   15    2    0



In [37]:
ceil(a)

ans =

    1   15    2    1



In [38]:
rand(3)

ans =

   0.95925   0.34514   0.99009
   0.28034   0.28936   0.16569
   0.89877   0.45414   0.50770



In [39]:
max(rand(3), rand(3))

ans =

   0.55976   0.20608   0.87110
   0.84416   0.72893   0.79551
   0.46581   0.58338   0.83710



In [40]:
max(A,[], 1)

ans =

   8   9   7



In [41]:
max(A,[], 2)

ans =

   8
   7
   9



In [42]:
max(A)

ans =

   8   9   7



In [43]:
max(max(A))

ans =  9


In [44]:
max(A(:))

ans =  9


In [45]:
A = magic(9)

A =

   47   58   69   80    1   12   23   34   45
   57   68   79    9   11   22   33   44   46
   67   78    8   10   21   32   43   54   56
   77    7   18   20   31   42   53   55   66
    6   17   19   30   41   52   63   65   76
   16   27   29   40   51   62   64   75    5
   26   28   39   50   61   72   74    4   15
   36   38   49   60   71   73    3   14   25
   37   48   59   70   81    2   13   24   35



In [46]:
sum(A, 1)

ans =

   369   369   369   369   369   369   369   369   369



In [47]:
sum(A,2)

ans =

   369
   369
   369
   369
   369
   369
   369
   369
   369



In [48]:
eye(9)

ans =

Diagonal Matrix

   1   0   0   0   0   0   0   0   0
   0   1   0   0   0   0   0   0   0
   0   0   1   0   0   0   0   0   0
   0   0   0   1   0   0   0   0   0
   0   0   0   0   1   0   0   0   0
   0   0   0   0   0   1   0   0   0
   0   0   0   0   0   0   1   0   0
   0   0   0   0   0   0   0   1   0
   0   0   0   0   0   0   0   0   1



In [49]:
A .* eye(9)

ans =

   47    0    0    0    0    0    0    0    0
    0   68    0    0    0    0    0    0    0
    0    0    8    0    0    0    0    0    0
    0    0    0   20    0    0    0    0    0
    0    0    0    0   41    0    0    0    0
    0    0    0    0    0   62    0    0    0
    0    0    0    0    0    0   74    0    0
    0    0    0    0    0    0    0   14    0
    0    0    0    0    0    0    0    0   35



In [50]:
sum(sum(A .* eye(9)))

ans =  369


In [51]:
flipud(eye(9))

ans =

Permutation Matrix

   0   0   0   0   0   0   0   0   1
   0   0   0   0   0   0   0   1   0
   0   0   0   0   0   0   1   0   0
   0   0   0   0   0   1   0   0   0
   0   0   0   0   1   0   0   0   0
   0   0   0   1   0   0   0   0   0
   0   0   1   0   0   0   0   0   0
   0   1   0   0   0   0   0   0   0
   1   0   0   0   0   0   0   0   0



In [52]:
sum(sum(A .* flipud(eye(9))))

ans =  369


In [53]:
A = magic(3)

A =

   8   1   6
   3   5   7
   4   9   2



In [54]:
pinv(A)

ans =

   0.147222  -0.144444   0.063889
  -0.061111   0.022222   0.105556
  -0.019444   0.188889  -0.102778



In [55]:
temp = pinv(A)

temp =

   0.147222  -0.144444   0.063889
  -0.061111   0.022222   0.105556
  -0.019444   0.188889  -0.102778



In [56]:
temp * A

ans =

   1.00000   0.00000  -0.00000
  -0.00000   1.00000   0.00000
   0.00000   0.00000   1.00000

